### ISSUE TITLE
Missing Hadamard Products in Forward pass

### ISSUE THREAD

**Issue by bkoyuncu** [ndrplz/ConvLSTM_pytorch#11]
First off thank you for the implementation. Are Hadamard products in the paper missing? Please see the image below and paper that I am referring to for clarification.

[Image for equations](https://qph.fs.quoracdn.net/main-qimg-1b1515ab2aee827a83d89759263a6dff)
[Paper](https://arxiv.org/abs/1506.04214)

**Comment by ndrplz** [comment]
The cell dynamic implemented in this repo is different from the one in the paper you mention.

Probably #8 will answer your question.

To be fair, a couple of years have passed and I can't remember right now why we chose to implement a slightly different dynamic than in the "original" paper. 

@DavideA, do you have a better memory?

**Comment by bkoyuncu** [comment]
Thank you, shoud have checked the prev questions first.

**Comment by gacuervol** [comment]
I’ve had the same question for a while, and after doing some research, I’d like to share what I found in case it helps someone else in the future:

In LSTM literature, the Hadamard product (∘) in the equations is known as a [peephole connection](https://ieeexplore.ieee.org/document/861302). However, many deep learning libraries don’t include these connections in their LSTM implementations. This is because they use a simplified version of LSTM that skips peephole connections. The benefit of this simplification is fewer parameters, and research shows it has minimal impact on performance. If you’re curious, this [article](https://ieeexplore.ieee.org/abstract/document/7508408) explains it well. For this reason, modern LSTMs usually don’t include peephole connections. Another usefull review is [this](https://ieeexplore.ieee.org/document/8737887)

As for ConvLSTMs, the paper by  [Shi et al.(2015)](https://arxiv.org/abs/1506.04214) uses equations based on the LSTM cell with peephole connections. So technically, Shi et al.(2015) introduces something like "ConvLSTMs with peephole connections." But since peephole connections aren’t essential, most modern ConvLSTM implementations (including those without the Hadamard product) represent a more efficient, simplified version. These are what we generally refer to as modern ConvLSTM cell, distinct from Shi et al.(2015)’s original version.
