### ISSUE TITLE
kernel_size = (2, 2) causes dimension issues

### ISSUE THREAD

**Issue by NicholasKiefer** [ndrplz/ConvLSTM_pytorch#27]
This code snippet taken and changed slightly from the docstring fails for me:
```
import torch
from CONVLSTM_Implementation import ConvLSTM
x = torch.rand((32, 10, 64, 128, 128))
convlstm = ConvLSTM(64, 16, (2, 2), 1, True, True, False)
_, last_states = convlstm(x)
```

with the following Error:

```
c_next = f * c_cur + i * g
RuntimeError: The size of tensor a (129) must match the size of tensor b (128) at non-singleton dimension 3
```
But I don't really know why. I guess I will use a different kernel_size for now.

**Comment by ndrplz** [comment]
Hi @NicholasKiefer ,

The issue is that the padding of the convolution is set to `kernel_size//2` ([here](https://github.com/ndrplz/ConvLSTM_pytorch/blob/9f662ba24b0a38e82cf0f5208c7f4859deb85ffe/convlstm.py#L29)) which doesn't really work for kernel size 2. Your output gets padded 1 pixel too much and becomes 129px which causes the complain you see in the stack trace

I would just stick to a different kernel size, e.g. 3

**Comment by NicholasKiefer** [comment]
Thank you for the quick answer, I thought it may have to do something with that. I'll keep to different kernel sizes though I am interested in how to make it work with kernel size 2. Setting the padding to zero doesn't help.
